/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.mydsl.services.MyDslGrammarAccess
import roboML.BinaryArithmetic
import roboML.Negative

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(Negative negative, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (variable : negative.variable) {
			variable.format
		}
		negative.expression.format
	}

	def dispatch void format(BinaryArithmetic binaryArithmetic, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (variable : binaryArithmetic.variable) {
			variable.format
		}
		for (expression : binaryArithmetic.expression) {
			expression.format
		}
	}
	
	// TODO: implement for CallExpr, VarExpr, Not, BinaryBool, SensorExpr
}
