/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.mydsl.services.MyDslGrammarAccess
import roboML.Loop
import roboML.RobotProgram

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(RobotProgram robotProgram, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (declaration : robotProgram.declaration) {
			declaration.format
		}
		for (instruction : robotProgram.instruction) {
			instruction.format
		}
		for (expression : robotProgram.expression) {
			expression.format
		}
	}

	def dispatch void format(Loop loop, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		loop.booleanexpr.format
		for (instruction : loop.instruction) {
			instruction.format
		}
	}
	
	// TODO: implement for Condition, Assignment, Block, Forward, Rotate, Left, Backward, Right, Speed, Not, BinaryBool, CallExpr, VarExpr, Negative, BinaryArithmetic, SensorExpr
}
