/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cType_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBoolParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRealParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Type returns Type:
		//    Type_Impl | Bool | Real;
		@Override public ParserRule getRule() { return rule; }
		
		//Type_Impl | Bool | Real
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Type_Impl
		public RuleCall getType_ImplParserRuleCall_0() { return cType_ImplParserRuleCall_0; }
		
		//Bool
		public RuleCall getBoolParserRuleCall_1() { return cBoolParserRuleCall_1; }
		
		//Real
		public RuleCall getRealParserRuleCall_2() { return cRealParserRuleCall_2; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallExprParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVarExprParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNegativeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBinaryArithmeticParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cNotParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cBinaryBoolParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cSensorExprParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Expression returns Expression:
		//    CallExpr | VarExpr | Negative | BinaryArithmetic | Not | BinaryBool | SensorExpr;
		@Override public ParserRule getRule() { return rule; }
		
		//CallExpr | VarExpr | Negative | BinaryArithmetic | Not | BinaryBool | SensorExpr
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallExpr
		public RuleCall getCallExprParserRuleCall_0() { return cCallExprParserRuleCall_0; }
		
		//VarExpr
		public RuleCall getVarExprParserRuleCall_1() { return cVarExprParserRuleCall_1; }
		
		//Negative
		public RuleCall getNegativeParserRuleCall_2() { return cNegativeParserRuleCall_2; }
		
		//BinaryArithmetic
		public RuleCall getBinaryArithmeticParserRuleCall_3() { return cBinaryArithmeticParserRuleCall_3; }
		
		//Not
		public RuleCall getNotParserRuleCall_4() { return cNotParserRuleCall_4; }
		
		//BinaryBool
		public RuleCall getBinaryBoolParserRuleCall_5() { return cBinaryBoolParserRuleCall_5; }
		
		//SensorExpr
		public RuleCall getSensorExprParserRuleCall_6() { return cSensorExprParserRuleCall_6; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Sensor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSensor_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSensorDistanceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSensorTimeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Sensor returns Sensor:
		//    Sensor_Impl | SensorDistance | SensorTime;
		@Override public ParserRule getRule() { return rule; }
		
		//Sensor_Impl | SensorDistance | SensorTime
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Sensor_Impl
		public RuleCall getSensor_ImplParserRuleCall_0() { return cSensor_ImplParserRuleCall_0; }
		
		//SensorDistance
		public RuleCall getSensorDistanceParserRuleCall_1() { return cSensorDistanceParserRuleCall_1; }
		
		//SensorTime
		public RuleCall getSensorTimeParserRuleCall_2() { return cSensorTimeParserRuleCall_2; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVariableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTypeTypeCrossReference_4_1_0 = (CrossReference)cTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cTypeTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cTypeTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Variable returns Variable:
		//    {Variable}
		//    'Variable'
		//    '{'
		//        ('name' name=String0)?
		//        ('type' type=[Type|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable}
		//'Variable'
		//'{'
		//    ('name' name=String0)?
		//    ('type' type=[Type|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//'Variable'
		public Keyword getVariableKeyword_1() { return cVariableKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//('type' type=[Type|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=[Type|EString]
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//[Type|EString]
		public CrossReference getTypeTypeCrossReference_4_1_0() { return cTypeTypeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTypeTypeEStringParserRuleCall_4_1_0_1() { return cTypeTypeEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class NegativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Negative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNegativeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVariableKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cVariableAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_2_2_0 = (RuleCall)cVariableAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cVariableAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_2_3_1_0 = (RuleCall)cVariableAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cExpressionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpressionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpressionExpressionParserRuleCall_4_0 = (RuleCall)cExpressionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Negative returns Negative:
		//    'Negative'
		//    '{'
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Negative'
		//'{'
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Negative'
		public Keyword getNegativeKeyword_0() { return cNegativeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'variable'
		public Keyword getVariableKeyword_2_0() { return cVariableKeyword_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_2_2() { return cVariableAssignment_2_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_2_2_0() { return cVariableVariableParserRuleCall_2_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_2_3_1() { return cVariableAssignment_2_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_2_3_1_0() { return cVariableVariableParserRuleCall_2_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
		
		//'expression'
		public Keyword getExpressionKeyword_3() { return cExpressionKeyword_3; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_4() { return cExpressionAssignment_4; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_4_0() { return cExpressionExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class BinaryArithmeticElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BinaryArithmetic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBinaryArithmeticKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOperationKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOperationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOperationArithmeticOperationEnumRuleCall_2_1_0 = (RuleCall)cOperationAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVariableKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cVariableAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_3_2_0 = (RuleCall)cVariableAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cVariableAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_3_3_1_0 = (RuleCall)cVariableAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cExpressionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpressionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpressionExpressionParserRuleCall_6_0 = (RuleCall)cExpressionAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cExpressionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_7_1_0 = (RuleCall)cExpressionAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//BinaryArithmetic returns BinaryArithmetic:
		//    'BinaryArithmetic'
		//    '{'
		//        ('operation' operation=ArithmeticOperation)?
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'BinaryArithmetic'
		//'{'
		//    ('operation' operation=ArithmeticOperation)?
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'BinaryArithmetic'
		public Keyword getBinaryArithmeticKeyword_0() { return cBinaryArithmeticKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('operation' operation=ArithmeticOperation)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'operation'
		public Keyword getOperationKeyword_2_0() { return cOperationKeyword_2_0; }
		
		//operation=ArithmeticOperation
		public Assignment getOperationAssignment_2_1() { return cOperationAssignment_2_1; }
		
		//ArithmeticOperation
		public RuleCall getOperationArithmeticOperationEnumRuleCall_2_1_0() { return cOperationArithmeticOperationEnumRuleCall_2_1_0; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'variable'
		public Keyword getVariableKeyword_3_0() { return cVariableKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_3_2() { return cVariableAssignment_3_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_3_2_0() { return cVariableVariableParserRuleCall_3_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_3_3_1() { return cVariableAssignment_3_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_3_3_1_0() { return cVariableVariableParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'expression'
		public Keyword getExpressionKeyword_4() { return cExpressionKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_6() { return cExpressionAssignment_6; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_6_0() { return cExpressionExpressionParserRuleCall_6_0; }
		
		//( "," expression+=Expression)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_7_1() { return cExpressionAssignment_7_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_7_1_0() { return cExpressionExpressionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class Type_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Type_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Type_Impl returns Type:
		//    {Type}
		//    'Type'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Type}
		//'Type'
		public Group getGroup() { return cGroup; }
		
		//{Type}
		public Action getTypeAction_0() { return cTypeAction_0; }
		
		//'Type'
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.String0");
		private final Keyword cStringKeyword = (Keyword)rule.eContents().get(1);
		
		//String0 returns type::String:
		//    'String' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'String'
		public Keyword getStringKeyword() { return cStringKeyword; }
	}
	public class BoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Bool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Bool returns Bool:
		//    {Bool}
		//    'Bool'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Bool}
		//'Bool'
		public Group getGroup() { return cGroup; }
		
		//{Bool}
		public Action getBoolAction_0() { return cBoolAction_0; }
		
		//'Bool'
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
	}
	public class RealElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Real");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRealAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRealKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUnitKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUnitAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cUnitUnitEnumRuleCall_3_1_0 = (RuleCall)cUnitAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Real returns Real:
		//    {Real}
		//    'Real'
		//    '{'
		//        ('unit' unit=Unit)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Real}
		//'Real'
		//'{'
		//    ('unit' unit=Unit)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Real}
		public Action getRealAction_0() { return cRealAction_0; }
		
		//'Real'
		public Keyword getRealKeyword_1() { return cRealKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('unit' unit=Unit)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'unit'
		public Keyword getUnitKeyword_3_0() { return cUnitKeyword_3_0; }
		
		//unit=Unit
		public Assignment getUnitAssignment_3_1() { return cUnitAssignment_3_1; }
		
		//Unit
		public RuleCall getUnitUnitEnumRuleCall_3_1_0() { return cUnitUnitEnumRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CallExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CallExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCallExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCallExprKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFonctionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFonctionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFonctionFonctionCrossReference_3_1_0 = (CrossReference)cFonctionAssignment_3_1.eContents().get(0);
		private final RuleCall cFonctionFonctionEStringParserRuleCall_3_1_0_1 = (RuleCall)cFonctionFonctionCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVariableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVariableAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_4_2_0 = (RuleCall)cVariableAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cVariableAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_4_3_1_0 = (RuleCall)cVariableAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cParametersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cParametersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cParametersExpressionParserRuleCall_5_2_0 = (RuleCall)cParametersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cParametersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cParametersExpressionParserRuleCall_5_3_1_0 = (RuleCall)cParametersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//CallExpr returns CallExpr:
		//    {CallExpr}
		//    'CallExpr'
		//    '{'
		//        ('fonction' fonction=[Fonction|EString])?
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//        ('parameters' '{' parameters+=Expression ( "," parameters+=Expression)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{CallExpr}
		//'CallExpr'
		//'{'
		//    ('fonction' fonction=[Fonction|EString])?
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    ('parameters' '{' parameters+=Expression ( "," parameters+=Expression)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{CallExpr}
		public Action getCallExprAction_0() { return cCallExprAction_0; }
		
		//'CallExpr'
		public Keyword getCallExprKeyword_1() { return cCallExprKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('fonction' fonction=[Fonction|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'fonction'
		public Keyword getFonctionKeyword_3_0() { return cFonctionKeyword_3_0; }
		
		//fonction=[Fonction|EString]
		public Assignment getFonctionAssignment_3_1() { return cFonctionAssignment_3_1; }
		
		//[Fonction|EString]
		public CrossReference getFonctionFonctionCrossReference_3_1_0() { return cFonctionFonctionCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFonctionFonctionEStringParserRuleCall_3_1_0_1() { return cFonctionFonctionEStringParserRuleCall_3_1_0_1; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'variable'
		public Keyword getVariableKeyword_4_0() { return cVariableKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_2() { return cVariableAssignment_4_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_2_0() { return cVariableVariableParserRuleCall_4_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_3_1() { return cVariableAssignment_4_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_3_1_0() { return cVariableVariableParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('parameters' '{' parameters+=Expression ( "," parameters+=Expression)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'parameters'
		public Keyword getParametersKeyword_5_0() { return cParametersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//parameters+=Expression
		public Assignment getParametersAssignment_5_2() { return cParametersAssignment_5_2; }
		
		//Expression
		public RuleCall getParametersExpressionParserRuleCall_5_2_0() { return cParametersExpressionParserRuleCall_5_2_0; }
		
		//( "," parameters+=Expression)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//parameters+=Expression
		public Assignment getParametersAssignment_5_3_1() { return cParametersAssignment_5_3_1; }
		
		//Expression
		public RuleCall getParametersExpressionParserRuleCall_5_3_1_0() { return cParametersExpressionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class VarExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.VarExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVarExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVarExprKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVariableRefKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cVariableRefAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cVariableRefVariableCrossReference_3_1_0 = (CrossReference)cVariableRefAssignment_3_1.eContents().get(0);
		private final RuleCall cVariableRefVariableEStringParserRuleCall_3_1_0_1 = (RuleCall)cVariableRefVariableCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVariableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVariableAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_4_2_0 = (RuleCall)cVariableAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cVariableAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_4_3_1_0 = (RuleCall)cVariableAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//VarExpr returns VarExpr:
		//    {VarExpr}
		//    'VarExpr'
		//    '{'
		//        ('variableRef' variableRef=[Variable|EString])?
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VarExpr}
		//'VarExpr'
		//'{'
		//    ('variableRef' variableRef=[Variable|EString])?
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VarExpr}
		public Action getVarExprAction_0() { return cVarExprAction_0; }
		
		//'VarExpr'
		public Keyword getVarExprKeyword_1() { return cVarExprKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('variableRef' variableRef=[Variable|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'variableRef'
		public Keyword getVariableRefKeyword_3_0() { return cVariableRefKeyword_3_0; }
		
		//variableRef=[Variable|EString]
		public Assignment getVariableRefAssignment_3_1() { return cVariableRefAssignment_3_1; }
		
		//[Variable|EString]
		public CrossReference getVariableRefVariableCrossReference_3_1_0() { return cVariableRefVariableCrossReference_3_1_0; }
		
		//EString
		public RuleCall getVariableRefVariableEStringParserRuleCall_3_1_0_1() { return cVariableRefVariableEStringParserRuleCall_3_1_0_1; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'variable'
		public Keyword getVariableKeyword_4_0() { return cVariableKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_2() { return cVariableAssignment_4_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_2_0() { return cVariableVariableParserRuleCall_4_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_3_1() { return cVariableAssignment_4_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_3_1_0() { return cVariableVariableParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class NotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Not");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNotKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVariableKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cVariableAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_2_2_0 = (RuleCall)cVariableAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cVariableAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_2_3_1_0 = (RuleCall)cVariableAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cExpressionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpressionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpressionExpressionParserRuleCall_4_0 = (RuleCall)cExpressionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Not returns Not:
		//    'Not'
		//    '{'
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Not'
		//'{'
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Not'
		public Keyword getNotKeyword_0() { return cNotKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'variable'
		public Keyword getVariableKeyword_2_0() { return cVariableKeyword_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_2_2() { return cVariableAssignment_2_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_2_2_0() { return cVariableVariableParserRuleCall_2_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_2_3_1() { return cVariableAssignment_2_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_2_3_1_0() { return cVariableVariableParserRuleCall_2_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
		
		//'expression'
		public Keyword getExpressionKeyword_3() { return cExpressionKeyword_3; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_4() { return cExpressionAssignment_4; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_4_0() { return cExpressionExpressionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class BinaryBoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BinaryBool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBinaryBoolKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOperationKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOperationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOperationBoolOperationEnumRuleCall_2_1_0 = (RuleCall)cOperationAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVariableKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cVariableAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_3_2_0 = (RuleCall)cVariableAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cVariableAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_3_3_1_0 = (RuleCall)cVariableAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cExpressionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpressionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpressionExpressionParserRuleCall_6_0 = (RuleCall)cExpressionAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cExpressionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_7_1_0 = (RuleCall)cExpressionAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//BinaryBool returns BinaryBool:
		//    'BinaryBool'
		//    '{'
		//        ('operation' operation=BoolOperation)?
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'BinaryBool'
		//'{'
		//    ('operation' operation=BoolOperation)?
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'BinaryBool'
		public Keyword getBinaryBoolKeyword_0() { return cBinaryBoolKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('operation' operation=BoolOperation)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'operation'
		public Keyword getOperationKeyword_2_0() { return cOperationKeyword_2_0; }
		
		//operation=BoolOperation
		public Assignment getOperationAssignment_2_1() { return cOperationAssignment_2_1; }
		
		//BoolOperation
		public RuleCall getOperationBoolOperationEnumRuleCall_2_1_0() { return cOperationBoolOperationEnumRuleCall_2_1_0; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'variable'
		public Keyword getVariableKeyword_3_0() { return cVariableKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_3_2() { return cVariableAssignment_3_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_3_2_0() { return cVariableVariableParserRuleCall_3_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_3_3_1() { return cVariableAssignment_3_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_3_3_1_0() { return cVariableVariableParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'expression'
		public Keyword getExpressionKeyword_4() { return cExpressionKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_6() { return cExpressionAssignment_6; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_6_0() { return cExpressionExpressionParserRuleCall_6_0; }
		
		//( "," expression+=Expression)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_7_1() { return cExpressionAssignment_7_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_7_1_0() { return cExpressionExpressionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class SensorExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SensorExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorExprKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSensorKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSensorAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cSensorSensorCrossReference_3_1_0 = (CrossReference)cSensorAssignment_3_1.eContents().get(0);
		private final RuleCall cSensorSensorEStringParserRuleCall_3_1_0_1 = (RuleCall)cSensorSensorCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVariableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVariableAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_4_2_0 = (RuleCall)cVariableAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cVariableAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_4_3_1_0 = (RuleCall)cVariableAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SensorExpr returns SensorExpr:
		//    {SensorExpr}
		//    'SensorExpr'
		//    '{'
		//        ('sensor' sensor=[Sensor|EString])?
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SensorExpr}
		//'SensorExpr'
		//'{'
		//    ('sensor' sensor=[Sensor|EString])?
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SensorExpr}
		public Action getSensorExprAction_0() { return cSensorExprAction_0; }
		
		//'SensorExpr'
		public Keyword getSensorExprKeyword_1() { return cSensorExprKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('sensor' sensor=[Sensor|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'sensor'
		public Keyword getSensorKeyword_3_0() { return cSensorKeyword_3_0; }
		
		//sensor=[Sensor|EString]
		public Assignment getSensorAssignment_3_1() { return cSensorAssignment_3_1; }
		
		//[Sensor|EString]
		public CrossReference getSensorSensorCrossReference_3_1_0() { return cSensorSensorCrossReference_3_1_0; }
		
		//EString
		public RuleCall getSensorSensorEStringParserRuleCall_3_1_0_1() { return cSensorSensorEStringParserRuleCall_3_1_0_1; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'variable'
		public Keyword getVariableKeyword_4_0() { return cVariableKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_2() { return cVariableAssignment_4_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_2_0() { return cVariableVariableParserRuleCall_4_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_3_1() { return cVariableAssignment_4_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_3_1_0() { return cVariableVariableParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FonctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Fonction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFonctionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFonctionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParameterKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParameterAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cParameterParameterCrossReference_4_2_0 = (CrossReference)cParameterAssignment_4_2.eContents().get(0);
		private final RuleCall cParameterParameterEStringParserRuleCall_4_2_0_1 = (RuleCall)cParameterParameterCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParameterAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cParameterParameterCrossReference_4_3_1_0 = (CrossReference)cParameterAssignment_4_3_1.eContents().get(0);
		private final RuleCall cParameterParameterEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cParameterParameterCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeReturnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeReturnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTypeReturnTypeCrossReference_5_1_0 = (CrossReference)cTypeReturnAssignment_5_1.eContents().get(0);
		private final RuleCall cTypeReturnTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cTypeReturnTypeCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Fonction returns Fonction:
		//    {Fonction}
		//    'Fonction'
		//    '{'
		//        ('name' name=String0)?
		//        ('parameter' '(' parameter+=[Parameter|EString] ( "," parameter+=[Parameter|EString])* ')' )?
		//        ('typeReturn' typeReturn=[Type|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Fonction}
		//'Fonction'
		//'{'
		//    ('name' name=String0)?
		//    ('parameter' '(' parameter+=[Parameter|EString] ( "," parameter+=[Parameter|EString])* ')' )?
		//    ('typeReturn' typeReturn=[Type|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Fonction}
		public Action getFonctionAction_0() { return cFonctionAction_0; }
		
		//'Fonction'
		public Keyword getFonctionKeyword_1() { return cFonctionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//('parameter' '(' parameter+=[Parameter|EString] ( "," parameter+=[Parameter|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parameter'
		public Keyword getParameterKeyword_4_0() { return cParameterKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//parameter+=[Parameter|EString]
		public Assignment getParameterAssignment_4_2() { return cParameterAssignment_4_2; }
		
		//[Parameter|EString]
		public CrossReference getParameterParameterCrossReference_4_2_0() { return cParameterParameterCrossReference_4_2_0; }
		
		//EString
		public RuleCall getParameterParameterEStringParserRuleCall_4_2_0_1() { return cParameterParameterEStringParserRuleCall_4_2_0_1; }
		
		//( "," parameter+=[Parameter|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parameter+=[Parameter|EString]
		public Assignment getParameterAssignment_4_3_1() { return cParameterAssignment_4_3_1; }
		
		//[Parameter|EString]
		public CrossReference getParameterParameterCrossReference_4_3_1_0() { return cParameterParameterCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getParameterParameterEStringParserRuleCall_4_3_1_0_1() { return cParameterParameterEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('typeReturn' typeReturn=[Type|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'typeReturn'
		public Keyword getTypeReturnKeyword_5_0() { return cTypeReturnKeyword_5_0; }
		
		//typeReturn=[Type|EString]
		public Assignment getTypeReturnAssignment_5_1() { return cTypeReturnAssignment_5_1; }
		
		//[Type|EString]
		public CrossReference getTypeReturnTypeCrossReference_5_1_0() { return cTypeReturnTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getTypeReturnTypeEStringParserRuleCall_5_1_0_1() { return cTypeReturnTypeEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTypeTypeCrossReference_4_1_0 = (CrossReference)cTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cTypeTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cTypeTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter returns Parameter:
		//    {Parameter}
		//    'Parameter'
		//    '{'
		//        ('name' name=String0)?
		//        ('type' type=[Type|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter}
		//'Parameter'
		//'{'
		//    ('name' name=String0)?
		//    ('type' type=[Type|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//('type' type=[Type|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=[Type|EString]
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//[Type|EString]
		public CrossReference getTypeTypeCrossReference_4_1_0() { return cTypeTypeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTypeTypeEStringParserRuleCall_4_1_0_1() { return cTypeTypeEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Sensor_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Sensor_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Sensor_Impl returns Sensor:
		//    {Sensor}
		//    'Sensor'
		//    '{'
		//        ('name' name=String0)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Sensor}
		//'Sensor'
		//'{'
		//    ('name' name=String0)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Sensor}
		public Action getSensorAction_0() { return cSensorAction_0; }
		
		//'Sensor'
		public Keyword getSensorKeyword_1() { return cSensorKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SensorDistanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SensorDistance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorDistanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorDistanceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SensorDistance returns SensorDistance:
		//    {SensorDistance}
		//    'SensorDistance'
		//    '{'
		//        ('name' name=String0)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SensorDistance}
		//'SensorDistance'
		//'{'
		//    ('name' name=String0)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SensorDistance}
		public Action getSensorDistanceAction_0() { return cSensorDistanceAction_0; }
		
		//'SensorDistance'
		public Keyword getSensorDistanceKeyword_1() { return cSensorDistanceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SensorTimeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SensorTime");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSensorTimeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSensorTimeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameString0ParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SensorTime returns SensorTime:
		//    {SensorTime}
		//    'SensorTime'
		//    '{'
		//        ('name' name=String0)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SensorTime}
		//'SensorTime'
		//'{'
		//    ('name' name=String0)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SensorTime}
		public Action getSensorTimeAction_0() { return cSensorTimeAction_0; }
		
		//'SensorTime'
		public Keyword getSensorTimeKeyword_1() { return cSensorTimeKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('name' name=String0)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'name'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=String0
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//String0
		public RuleCall getNameString0ParserRuleCall_3_1_0() { return cNameString0ParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID ;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class UnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Unit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMMEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMMMMKeyword_0_0 = (Keyword)cMMEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cKMEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cKMKMKeyword_1_0 = (Keyword)cKMEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCMEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCMCMKeyword_2_0 = (Keyword)cCMEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMMKeyword_3_0 = (Keyword)cMEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDMEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDMDMKeyword_4_0 = (Keyword)cDMEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cHMEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cHMHMKeyword_5_0 = (Keyword)cHMEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDAMEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDAMDAMKeyword_6_0 = (Keyword)cDAMEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cRADEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cRADRADKeyword_7_0 = (Keyword)cRADEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum Unit returns Unit:
		//                MM = 'MM' | KM = 'KM' | CM = 'CM' | M = 'M' | DM = 'DM' | HM = 'HM' | DAM = 'DAM' | RAD = 'RAD';
		public EnumRule getRule() { return rule; }
		
		//MM = 'MM' | KM = 'KM' | CM = 'CM' | M = 'M' | DM = 'DM' | HM = 'HM' | DAM = 'DAM' | RAD = 'RAD'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MM = 'MM'
		public EnumLiteralDeclaration getMMEnumLiteralDeclaration_0() { return cMMEnumLiteralDeclaration_0; }
		
		//'MM'
		public Keyword getMMMMKeyword_0_0() { return cMMMMKeyword_0_0; }
		
		//KM = 'KM'
		public EnumLiteralDeclaration getKMEnumLiteralDeclaration_1() { return cKMEnumLiteralDeclaration_1; }
		
		//'KM'
		public Keyword getKMKMKeyword_1_0() { return cKMKMKeyword_1_0; }
		
		//CM = 'CM'
		public EnumLiteralDeclaration getCMEnumLiteralDeclaration_2() { return cCMEnumLiteralDeclaration_2; }
		
		//'CM'
		public Keyword getCMCMKeyword_2_0() { return cCMCMKeyword_2_0; }
		
		//M = 'M'
		public EnumLiteralDeclaration getMEnumLiteralDeclaration_3() { return cMEnumLiteralDeclaration_3; }
		
		//'M'
		public Keyword getMMKeyword_3_0() { return cMMKeyword_3_0; }
		
		//DM = 'DM'
		public EnumLiteralDeclaration getDMEnumLiteralDeclaration_4() { return cDMEnumLiteralDeclaration_4; }
		
		//'DM'
		public Keyword getDMDMKeyword_4_0() { return cDMDMKeyword_4_0; }
		
		//HM = 'HM'
		public EnumLiteralDeclaration getHMEnumLiteralDeclaration_5() { return cHMEnumLiteralDeclaration_5; }
		
		//'HM'
		public Keyword getHMHMKeyword_5_0() { return cHMHMKeyword_5_0; }
		
		//DAM = 'DAM'
		public EnumLiteralDeclaration getDAMEnumLiteralDeclaration_6() { return cDAMEnumLiteralDeclaration_6; }
		
		//'DAM'
		public Keyword getDAMDAMKeyword_6_0() { return cDAMDAMKeyword_6_0; }
		
		//RAD = 'RAD'
		public EnumLiteralDeclaration getRADEnumLiteralDeclaration_7() { return cRADEnumLiteralDeclaration_7; }
		
		//'RAD'
		public Keyword getRADRADKeyword_7_0() { return cRADRADKeyword_7_0; }
	}
	public class BoolOperationElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BoolOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINFEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINFINFKeyword_0_0 = (Keyword)cINFEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSUPEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSUPSUPKeyword_1_0 = (Keyword)cSUPEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cINF_EQEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cINF_EQINF_EQKeyword_2_0 = (Keyword)cINF_EQEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEQEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEQEQKeyword_3_0 = (Keyword)cEQEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSUP_EQEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSUP_EQSUP_EQKeyword_4_0 = (Keyword)cSUP_EQEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cNEQEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cNEQNEQKeyword_5_0 = (Keyword)cNEQEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cORORKeyword_6_0 = (Keyword)cOREnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cANDANDKeyword_7_0 = (Keyword)cANDEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum BoolOperation returns BoolOperation:
		//                INF = 'INF' | SUP = 'SUP' | INF_EQ = 'INF_EQ' | EQ = 'EQ' | SUP_EQ = 'SUP_EQ' | NEQ = 'NEQ' | OR = 'OR' | AND = 'AND';
		public EnumRule getRule() { return rule; }
		
		//INF = 'INF' | SUP = 'SUP' | INF_EQ = 'INF_EQ' | EQ = 'EQ' | SUP_EQ = 'SUP_EQ' | NEQ = 'NEQ' | OR = 'OR' | AND = 'AND'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INF = 'INF'
		public EnumLiteralDeclaration getINFEnumLiteralDeclaration_0() { return cINFEnumLiteralDeclaration_0; }
		
		//'INF'
		public Keyword getINFINFKeyword_0_0() { return cINFINFKeyword_0_0; }
		
		//SUP = 'SUP'
		public EnumLiteralDeclaration getSUPEnumLiteralDeclaration_1() { return cSUPEnumLiteralDeclaration_1; }
		
		//'SUP'
		public Keyword getSUPSUPKeyword_1_0() { return cSUPSUPKeyword_1_0; }
		
		//INF_EQ = 'INF_EQ'
		public EnumLiteralDeclaration getINF_EQEnumLiteralDeclaration_2() { return cINF_EQEnumLiteralDeclaration_2; }
		
		//'INF_EQ'
		public Keyword getINF_EQINF_EQKeyword_2_0() { return cINF_EQINF_EQKeyword_2_0; }
		
		//EQ = 'EQ'
		public EnumLiteralDeclaration getEQEnumLiteralDeclaration_3() { return cEQEnumLiteralDeclaration_3; }
		
		//'EQ'
		public Keyword getEQEQKeyword_3_0() { return cEQEQKeyword_3_0; }
		
		//SUP_EQ = 'SUP_EQ'
		public EnumLiteralDeclaration getSUP_EQEnumLiteralDeclaration_4() { return cSUP_EQEnumLiteralDeclaration_4; }
		
		//'SUP_EQ'
		public Keyword getSUP_EQSUP_EQKeyword_4_0() { return cSUP_EQSUP_EQKeyword_4_0; }
		
		//NEQ = 'NEQ'
		public EnumLiteralDeclaration getNEQEnumLiteralDeclaration_5() { return cNEQEnumLiteralDeclaration_5; }
		
		//'NEQ'
		public Keyword getNEQNEQKeyword_5_0() { return cNEQNEQKeyword_5_0; }
		
		//OR = 'OR'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_6() { return cOREnumLiteralDeclaration_6; }
		
		//'OR'
		public Keyword getORORKeyword_6_0() { return cORORKeyword_6_0; }
		
		//AND = 'AND'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_7() { return cANDEnumLiteralDeclaration_7; }
		
		//'AND'
		public Keyword getANDANDKeyword_7_0() { return cANDANDKeyword_7_0; }
	}
	public class ArithmeticOperationElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArithmeticOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cADDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cADDADDKeyword_0_0 = (Keyword)cADDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSUBEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSUBSUBKeyword_1_0 = (Keyword)cSUBEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDIVEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDIVDIVKeyword_2_0 = (Keyword)cDIVEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMULTEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMULTMULTKeyword_3_0 = (Keyword)cMULTEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ArithmeticOperation returns ArithmeticOperation:
		//                ADD = 'ADD' | SUB = 'SUB' | DIV = 'DIV' | MULT = 'MULT';
		public EnumRule getRule() { return rule; }
		
		//ADD = 'ADD' | SUB = 'SUB' | DIV = 'DIV' | MULT = 'MULT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ADD = 'ADD'
		public EnumLiteralDeclaration getADDEnumLiteralDeclaration_0() { return cADDEnumLiteralDeclaration_0; }
		
		//'ADD'
		public Keyword getADDADDKeyword_0_0() { return cADDADDKeyword_0_0; }
		
		//SUB = 'SUB'
		public EnumLiteralDeclaration getSUBEnumLiteralDeclaration_1() { return cSUBEnumLiteralDeclaration_1; }
		
		//'SUB'
		public Keyword getSUBSUBKeyword_1_0() { return cSUBSUBKeyword_1_0; }
		
		//DIV = 'DIV'
		public EnumLiteralDeclaration getDIVEnumLiteralDeclaration_2() { return cDIVEnumLiteralDeclaration_2; }
		
		//'DIV'
		public Keyword getDIVDIVKeyword_2_0() { return cDIVDIVKeyword_2_0; }
		
		//MULT = 'MULT'
		public EnumLiteralDeclaration getMULTEnumLiteralDeclaration_3() { return cMULTEnumLiteralDeclaration_3; }
		
		//'MULT'
		public Keyword getMULTMULTKeyword_3_0() { return cMULTMULTKeyword_3_0; }
	}
	
	private final TypeElements pType;
	private final ExpressionElements pExpression;
	private final SensorElements pSensor;
	private final VariableElements pVariable;
	private final NegativeElements pNegative;
	private final BinaryArithmeticElements pBinaryArithmetic;
	private final Type_ImplElements pType_Impl;
	private final String0Elements pString0;
	private final BoolElements pBool;
	private final RealElements pReal;
	private final UnitElements eUnit;
	private final CallExprElements pCallExpr;
	private final VarExprElements pVarExpr;
	private final NotElements pNot;
	private final BinaryBoolElements pBinaryBool;
	private final SensorExprElements pSensorExpr;
	private final FonctionElements pFonction;
	private final ParameterElements pParameter;
	private final BoolOperationElements eBoolOperation;
	private final Sensor_ImplElements pSensor_Impl;
	private final SensorDistanceElements pSensorDistance;
	private final SensorTimeElements pSensorTime;
	private final ArithmeticOperationElements eArithmeticOperation;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pType = new TypeElements();
		this.pExpression = new ExpressionElements();
		this.pSensor = new SensorElements();
		this.pVariable = new VariableElements();
		this.pNegative = new NegativeElements();
		this.pBinaryArithmetic = new BinaryArithmeticElements();
		this.pType_Impl = new Type_ImplElements();
		this.pString0 = new String0Elements();
		this.pBool = new BoolElements();
		this.pReal = new RealElements();
		this.eUnit = new UnitElements();
		this.pCallExpr = new CallExprElements();
		this.pVarExpr = new VarExprElements();
		this.pNot = new NotElements();
		this.pBinaryBool = new BinaryBoolElements();
		this.pSensorExpr = new SensorExprElements();
		this.pFonction = new FonctionElements();
		this.pParameter = new ParameterElements();
		this.eBoolOperation = new BoolOperationElements();
		this.pSensor_Impl = new Sensor_ImplElements();
		this.pSensorDistance = new SensorDistanceElements();
		this.pSensorTime = new SensorTimeElements();
		this.eArithmeticOperation = new ArithmeticOperationElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Type returns Type:
	//    Type_Impl | Bool | Real;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Expression returns Expression:
	//    CallExpr | VarExpr | Negative | BinaryArithmetic | Not | BinaryBool | SensorExpr;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Sensor returns Sensor:
	//    Sensor_Impl | SensorDistance | SensorTime;
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//Variable returns Variable:
	//    {Variable}
	//    'Variable'
	//    '{'
	//        ('name' name=String0)?
	//        ('type' type=[Type|EString])?
	//    '}';
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Negative returns Negative:
	//    'Negative'
	//    '{'
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//        'expression' expression=Expression
	//    '}';
	public NegativeElements getNegativeAccess() {
		return pNegative;
	}
	
	public ParserRule getNegativeRule() {
		return getNegativeAccess().getRule();
	}
	
	//BinaryArithmetic returns BinaryArithmetic:
	//    'BinaryArithmetic'
	//    '{'
	//        ('operation' operation=ArithmeticOperation)?
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
	//    '}';
	public BinaryArithmeticElements getBinaryArithmeticAccess() {
		return pBinaryArithmetic;
	}
	
	public ParserRule getBinaryArithmeticRule() {
		return getBinaryArithmeticAccess().getRule();
	}
	
	//Type_Impl returns Type:
	//    {Type}
	//    'Type'
	//    ;
	public Type_ImplElements getType_ImplAccess() {
		return pType_Impl;
	}
	
	public ParserRule getType_ImplRule() {
		return getType_ImplAccess().getRule();
	}
	
	//String0 returns type::String:
	//    'String' /* TODO: implement this rule and an appropriate IValueConverter */;
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//Bool returns Bool:
	//    {Bool}
	//    'Bool'
	//    ;
	public BoolElements getBoolAccess() {
		return pBool;
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//Real returns Real:
	//    {Real}
	//    'Real'
	//    '{'
	//        ('unit' unit=Unit)?
	//    '}';
	public RealElements getRealAccess() {
		return pReal;
	}
	
	public ParserRule getRealRule() {
		return getRealAccess().getRule();
	}
	
	//enum Unit returns Unit:
	//                MM = 'MM' | KM = 'KM' | CM = 'CM' | M = 'M' | DM = 'DM' | HM = 'HM' | DAM = 'DAM' | RAD = 'RAD';
	public UnitElements getUnitAccess() {
		return eUnit;
	}
	
	public EnumRule getUnitRule() {
		return getUnitAccess().getRule();
	}
	
	//CallExpr returns CallExpr:
	//    {CallExpr}
	//    'CallExpr'
	//    '{'
	//        ('fonction' fonction=[Fonction|EString])?
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//        ('parameters' '{' parameters+=Expression ( "," parameters+=Expression)* '}' )?
	//    '}';
	public CallExprElements getCallExprAccess() {
		return pCallExpr;
	}
	
	public ParserRule getCallExprRule() {
		return getCallExprAccess().getRule();
	}
	
	//VarExpr returns VarExpr:
	//    {VarExpr}
	//    'VarExpr'
	//    '{'
	//        ('variableRef' variableRef=[Variable|EString])?
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//    '}';
	public VarExprElements getVarExprAccess() {
		return pVarExpr;
	}
	
	public ParserRule getVarExprRule() {
		return getVarExprAccess().getRule();
	}
	
	//Not returns Not:
	//    'Not'
	//    '{'
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//        'expression' expression=Expression
	//    '}';
	public NotElements getNotAccess() {
		return pNot;
	}
	
	public ParserRule getNotRule() {
		return getNotAccess().getRule();
	}
	
	//BinaryBool returns BinaryBool:
	//    'BinaryBool'
	//    '{'
	//        ('operation' operation=BoolOperation)?
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
	//    '}';
	public BinaryBoolElements getBinaryBoolAccess() {
		return pBinaryBool;
	}
	
	public ParserRule getBinaryBoolRule() {
		return getBinaryBoolAccess().getRule();
	}
	
	//SensorExpr returns SensorExpr:
	//    {SensorExpr}
	//    'SensorExpr'
	//    '{'
	//        ('sensor' sensor=[Sensor|EString])?
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//    '}';
	public SensorExprElements getSensorExprAccess() {
		return pSensorExpr;
	}
	
	public ParserRule getSensorExprRule() {
		return getSensorExprAccess().getRule();
	}
	
	//Fonction returns Fonction:
	//    {Fonction}
	//    'Fonction'
	//    '{'
	//        ('name' name=String0)?
	//        ('parameter' '(' parameter+=[Parameter|EString] ( "," parameter+=[Parameter|EString])* ')' )?
	//        ('typeReturn' typeReturn=[Type|EString])?
	//    '}';
	public FonctionElements getFonctionAccess() {
		return pFonction;
	}
	
	public ParserRule getFonctionRule() {
		return getFonctionAccess().getRule();
	}
	
	//Parameter returns Parameter:
	//    {Parameter}
	//    'Parameter'
	//    '{'
	//        ('name' name=String0)?
	//        ('type' type=[Type|EString])?
	//    '}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//enum BoolOperation returns BoolOperation:
	//                INF = 'INF' | SUP = 'SUP' | INF_EQ = 'INF_EQ' | EQ = 'EQ' | SUP_EQ = 'SUP_EQ' | NEQ = 'NEQ' | OR = 'OR' | AND = 'AND';
	public BoolOperationElements getBoolOperationAccess() {
		return eBoolOperation;
	}
	
	public EnumRule getBoolOperationRule() {
		return getBoolOperationAccess().getRule();
	}
	
	//Sensor_Impl returns Sensor:
	//    {Sensor}
	//    'Sensor'
	//    '{'
	//        ('name' name=String0)?
	//    '}';
	public Sensor_ImplElements getSensor_ImplAccess() {
		return pSensor_Impl;
	}
	
	public ParserRule getSensor_ImplRule() {
		return getSensor_ImplAccess().getRule();
	}
	
	//SensorDistance returns SensorDistance:
	//    {SensorDistance}
	//    'SensorDistance'
	//    '{'
	//        ('name' name=String0)?
	//    '}';
	public SensorDistanceElements getSensorDistanceAccess() {
		return pSensorDistance;
	}
	
	public ParserRule getSensorDistanceRule() {
		return getSensorDistanceAccess().getRule();
	}
	
	//SensorTime returns SensorTime:
	//    {SensorTime}
	//    'SensorTime'
	//    '{'
	//        ('name' name=String0)?
	//    '}';
	public SensorTimeElements getSensorTimeAccess() {
		return pSensorTime;
	}
	
	public ParserRule getSensorTimeRule() {
		return getSensorTimeAccess().getRule();
	}
	
	//enum ArithmeticOperation returns ArithmeticOperation:
	//                ADD = 'ADD' | SUB = 'SUB' | DIV = 'DIV' | MULT = 'MULT';
	public ArithmeticOperationElements getArithmeticOperationAccess() {
		return eArithmeticOperation;
	}
	
	public EnumRule getArithmeticOperationRule() {
		return getArithmeticOperationAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID ;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
