/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import roboML.Assignment;
import roboML.Backward;
import roboML.BinaryArithmetic;
import roboML.BinaryBool;
import roboML.Block;
import roboML.Bool;
import roboML.Call;
import roboML.CallExpr;
import roboML.Condition;
import roboML.Fonction;
import roboML.Forward;
import roboML.Left;
import roboML.Loop;
import roboML.Negative;
import roboML.Not;
import roboML.Real;
import roboML.Right;
import roboML.RoboMLPackage;
import roboML.RobotProgram;
import roboML.Rotate;
import roboML.Sensor;
import roboML.SensorDistance;
import roboML.SensorExpr;
import roboML.SensorTime;
import roboML.Speed;
import roboML.Type;
import roboML.VarExpr;
import roboML.Variable;
import roboML.return;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RoboMLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RoboMLPackage.ASSIGNMENT:
				sequence_Assignment(context, (Assignment) semanticObject); 
				return; 
			case RoboMLPackage.BACKWARD:
				sequence_Backward(context, (Backward) semanticObject); 
				return; 
			case RoboMLPackage.BINARY_ARITHMETIC:
				sequence_BinaryArithmetic(context, (BinaryArithmetic) semanticObject); 
				return; 
			case RoboMLPackage.BINARY_BOOL:
				sequence_BinaryBool(context, (BinaryBool) semanticObject); 
				return; 
			case RoboMLPackage.BLOCK:
				sequence_Block(context, (Block) semanticObject); 
				return; 
			case RoboMLPackage.BOOL:
				sequence_Bool(context, (Bool) semanticObject); 
				return; 
			case RoboMLPackage.CALL:
				sequence_Call(context, (Call) semanticObject); 
				return; 
			case RoboMLPackage.CALL_EXPR:
				sequence_CallExpr(context, (CallExpr) semanticObject); 
				return; 
			case RoboMLPackage.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case RoboMLPackage.FONCTION:
				sequence_Fonction(context, (Fonction) semanticObject); 
				return; 
			case RoboMLPackage.FORWARD:
				sequence_Forward(context, (Forward) semanticObject); 
				return; 
			case RoboMLPackage.LEFT:
				sequence_Left(context, (Left) semanticObject); 
				return; 
			case RoboMLPackage.LOOP:
				sequence_Loop(context, (Loop) semanticObject); 
				return; 
			case RoboMLPackage.NEGATIVE:
				sequence_Negative(context, (Negative) semanticObject); 
				return; 
			case RoboMLPackage.NOT:
				sequence_Not(context, (Not) semanticObject); 
				return; 
			case RoboMLPackage.PARAMETER:
				sequence_Parameter(context, (roboML.Parameter) semanticObject); 
				return; 
			case RoboMLPackage.REAL:
				sequence_Real(context, (Real) semanticObject); 
				return; 
			case RoboMLPackage.RIGHT:
				sequence_Right(context, (Right) semanticObject); 
				return; 
			case RoboMLPackage.ROBOT_PROGRAM:
				sequence_RobotProgram(context, (RobotProgram) semanticObject); 
				return; 
			case RoboMLPackage.ROTATE:
				sequence_Rotate(context, (Rotate) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR:
				sequence_Sensor_Impl(context, (Sensor) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_DISTANCE:
				sequence_SensorDistance(context, (SensorDistance) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_EXPR:
				sequence_SensorExpr(context, (SensorExpr) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_TIME:
				sequence_SensorTime(context, (SensorTime) semanticObject); 
				return; 
			case RoboMLPackage.SPEED:
				sequence_Speed(context, (Speed) semanticObject); 
				return; 
			case RoboMLPackage.TYPE:
				sequence_Type_Impl(context, (Type) semanticObject); 
				return; 
			case RoboMLPackage.VAR_EXPR:
				sequence_VarExpr(context, (VarExpr) semanticObject); 
				return; 
			case RoboMLPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			case RoboMLPackage.RETURN:
				sequence_return(context, (return) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Assignment
	 *     Assignment returns Assignment
	 *
	 * Constraint:
	 *     (variable=[Variable|EString]? expression=Expression?)
	 * </pre>
	 */
	protected void sequence_Assignment(ISerializationContext context, Assignment semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Backward
	 *     Backward returns Backward
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Backward(ISerializationContext context, Backward semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns BinaryArithmetic
	 *     BinaryArithmetic returns BinaryArithmetic
	 *
	 * Constraint:
	 *     (operation=ArithmeticOperation? (variable+=Variable variable+=Variable*)? expression+=Expression expression+=Expression*)
	 * </pre>
	 */
	protected void sequence_BinaryArithmetic(ISerializationContext context, BinaryArithmetic semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns BinaryBool
	 *     BooleanExpr returns BinaryBool
	 *     BinaryBool returns BinaryBool
	 *
	 * Constraint:
	 *     (operation=BoolOperation? (variable+=Variable variable+=Variable*)? expression+=Expression expression+=Expression*)
	 * </pre>
	 */
	protected void sequence_BinaryBool(ISerializationContext context, BinaryBool semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Block
	 *     Block returns Block
	 *
	 * Constraint:
	 *     (instruction+=Instruction instruction+=Instruction*)?
	 * </pre>
	 */
	protected void sequence_Block(ISerializationContext context, Block semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Bool
	 *     Bool returns Bool
	 *
	 * Constraint:
	 *     {Bool}
	 * </pre>
	 */
	protected void sequence_Bool(ISerializationContext context, Bool semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns CallExpr
	 *     CallExpr returns CallExpr
	 *
	 * Constraint:
	 *     (fonction=[Fonction|EString]? (variable+=Variable variable+=Variable*)? (parameters+=Expression parameters+=Expression*)?)
	 * </pre>
	 */
	protected void sequence_CallExpr(ISerializationContext context, CallExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Call
	 *     Call returns Call
	 *
	 * Constraint:
	 *     ((parameters+=[Expression|EString] parameters+=[Expression|EString]*)? fonction=[Fonction|EString]?)
	 * </pre>
	 */
	protected void sequence_Call(ISerializationContext context, Call semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Condition
	 *     Condition returns Condition
	 *
	 * Constraint:
	 *     (booleanexpr=BooleanExpr? if=Instruction? else=Instruction?)
	 * </pre>
	 */
	protected void sequence_Condition(ISerializationContext context, Condition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns Fonction
	 *     Fonction returns Fonction
	 *
	 * Constraint:
	 *     (name=EString (parameter+=[Parameter|EString] parameter+=[Parameter|EString]*)? typeReturn=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Fonction(ISerializationContext context, Fonction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Forward
	 *     Forward returns Forward
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Forward(ISerializationContext context, Forward semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Left
	 *     Left returns Left
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Left(ISerializationContext context, Left semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Loop
	 *     Loop returns Loop
	 *
	 * Constraint:
	 *     (booleanexpr=BooleanExpr? (instruction+=Instruction instruction+=Instruction*)?)
	 * </pre>
	 */
	protected void sequence_Loop(ISerializationContext context, Loop semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Negative
	 *     Negative returns Negative
	 *
	 * Constraint:
	 *     ((variable+=Variable variable+=Variable*)? expression=Expression)
	 * </pre>
	 */
	protected void sequence_Negative(ISerializationContext context, Negative semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Not
	 *     BooleanExpr returns Not
	 *     Not returns Not
	 *
	 * Constraint:
	 *     ((variable+=Variable variable+=Variable*)? expression=Expression)
	 * </pre>
	 */
	protected void sequence_Not(ISerializationContext context, Not semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (name=EString type=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Parameter(ISerializationContext context, roboML.Parameter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Real
	 *     Real returns Real
	 *
	 * Constraint:
	 *     unit=Unit?
	 * </pre>
	 */
	protected void sequence_Real(ISerializationContext context, Real semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Right
	 *     Right returns Right
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Right(ISerializationContext context, Right semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RobotProgram returns RobotProgram
	 *
	 * Constraint:
	 *     (
	 *         (declaration+=Declaration declaration+=Declaration*)? 
	 *         (instruction+=Instruction instruction+=Instruction*)? 
	 *         (expression+=Expression expression+=Expression*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_RobotProgram(ISerializationContext context, RobotProgram semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Rotate
	 *     Rotate returns Rotate
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Rotate(ISerializationContext context, Rotate semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns SensorDistance
	 *     Sensor returns SensorDistance
	 *     SensorDistance returns SensorDistance
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_SensorDistance(ISerializationContext context, SensorDistance semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RoboMLPackage.Literals.SENSOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RoboMLPackage.Literals.SENSOR__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSensorDistanceAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns SensorExpr
	 *     SensorExpr returns SensorExpr
	 *
	 * Constraint:
	 *     (sensor=[Sensor|EString]? (variable+=Variable variable+=Variable*)?)
	 * </pre>
	 */
	protected void sequence_SensorExpr(ISerializationContext context, SensorExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns SensorTime
	 *     Sensor returns SensorTime
	 *     SensorTime returns SensorTime
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_SensorTime(ISerializationContext context, SensorTime semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RoboMLPackage.Literals.SENSOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RoboMLPackage.Literals.SENSOR__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSensorTimeAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns Sensor
	 *     Sensor returns Sensor
	 *     Sensor_Impl returns Sensor
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Sensor_Impl(ISerializationContext context, Sensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RoboMLPackage.Literals.SENSOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RoboMLPackage.Literals.SENSOR__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSensor_ImplAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns Speed
	 *     Speed returns Speed
	 *
	 * Constraint:
	 *     parameters=Expression?
	 * </pre>
	 */
	protected void sequence_Speed(ISerializationContext context, Speed semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Type
	 *     Type_Impl returns Type
	 *
	 * Constraint:
	 *     {Type}
	 * </pre>
	 */
	protected void sequence_Type_Impl(ISerializationContext context, Type semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns VarExpr
	 *     VarExpr returns VarExpr
	 *
	 * Constraint:
	 *     (variableRef=[Variable|EString]? (variable+=Variable variable+=Variable*)?)
	 * </pre>
	 */
	protected void sequence_VarExpr(ISerializationContext context, VarExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns Variable
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     (name=EString type=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns return
	 *     return returns return
	 *
	 * Constraint:
	 *     expression=[Expression|EString]?
	 * </pre>
	 */
	protected void sequence_return(ISerializationContext context, return semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
