/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import roboML.BinaryArithmetic;
import roboML.BinaryBool;
import roboML.Bool;
import roboML.CallExpr;
import roboML.Fonction;
import roboML.Negative;
import roboML.Not;
import roboML.Real;
import roboML.RoboMLPackage;
import roboML.Sensor;
import roboML.SensorDistance;
import roboML.SensorExpr;
import roboML.SensorTime;
import roboML.Type;
import roboML.VarExpr;
import roboML.Variable;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RoboMLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RoboMLPackage.BINARY_ARITHMETIC:
				sequence_BinaryArithmetic(context, (BinaryArithmetic) semanticObject); 
				return; 
			case RoboMLPackage.BINARY_BOOL:
				sequence_BinaryBool(context, (BinaryBool) semanticObject); 
				return; 
			case RoboMLPackage.BOOL:
				sequence_Bool(context, (Bool) semanticObject); 
				return; 
			case RoboMLPackage.CALL_EXPR:
				sequence_CallExpr(context, (CallExpr) semanticObject); 
				return; 
			case RoboMLPackage.FONCTION:
				sequence_Fonction(context, (Fonction) semanticObject); 
				return; 
			case RoboMLPackage.NEGATIVE:
				sequence_Negative(context, (Negative) semanticObject); 
				return; 
			case RoboMLPackage.NOT:
				sequence_Not(context, (Not) semanticObject); 
				return; 
			case RoboMLPackage.PARAMETER:
				sequence_Parameter(context, (roboML.Parameter) semanticObject); 
				return; 
			case RoboMLPackage.REAL:
				sequence_Real(context, (Real) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR:
				sequence_Sensor_Impl(context, (Sensor) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_DISTANCE:
				sequence_SensorDistance(context, (SensorDistance) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_EXPR:
				sequence_SensorExpr(context, (SensorExpr) semanticObject); 
				return; 
			case RoboMLPackage.SENSOR_TIME:
				sequence_SensorTime(context, (SensorTime) semanticObject); 
				return; 
			case RoboMLPackage.TYPE:
				sequence_Type_Impl(context, (Type) semanticObject); 
				return; 
			case RoboMLPackage.VAR_EXPR:
				sequence_VarExpr(context, (VarExpr) semanticObject); 
				return; 
			case RoboMLPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns BinaryArithmetic
	 *     BinaryArithmetic returns BinaryArithmetic
	 *
	 * Constraint:
	 *     (operation=ArithmeticOperation? (variable+=Variable variable+=Variable*)? expression+=Expression expression+=Expression*)
	 * </pre>
	 */
	protected void sequence_BinaryArithmetic(ISerializationContext context, BinaryArithmetic semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns BinaryBool
	 *     BinaryBool returns BinaryBool
	 *
	 * Constraint:
	 *     (operation=BoolOperation? (variable+=Variable variable+=Variable*)? expression+=Expression expression+=Expression*)
	 * </pre>
	 */
	protected void sequence_BinaryBool(ISerializationContext context, BinaryBool semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Bool
	 *     Bool returns Bool
	 *
	 * Constraint:
	 *     {Bool}
	 * </pre>
	 */
	protected void sequence_Bool(ISerializationContext context, Bool semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns CallExpr
	 *     CallExpr returns CallExpr
	 *
	 * Constraint:
	 *     (fonction=[Fonction|EString]? (variable+=Variable variable+=Variable*)? (parameters+=Expression parameters+=Expression*)?)
	 * </pre>
	 */
	protected void sequence_CallExpr(ISerializationContext context, CallExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Fonction returns Fonction
	 *
	 * Constraint:
	 *     (name=String0? (parameter+=[Parameter|EString] parameter+=[Parameter|EString]*)? typeReturn=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Fonction(ISerializationContext context, Fonction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Negative
	 *     Negative returns Negative
	 *
	 * Constraint:
	 *     ((variable+=Variable variable+=Variable*)? expression=Expression)
	 * </pre>
	 */
	protected void sequence_Negative(ISerializationContext context, Negative semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Not
	 *     Not returns Not
	 *
	 * Constraint:
	 *     ((variable+=Variable variable+=Variable*)? expression=Expression)
	 * </pre>
	 */
	protected void sequence_Not(ISerializationContext context, Not semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (name=String0? type=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Parameter(ISerializationContext context, roboML.Parameter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Real
	 *     Real returns Real
	 *
	 * Constraint:
	 *     unit=Unit?
	 * </pre>
	 */
	protected void sequence_Real(ISerializationContext context, Real semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Sensor returns SensorDistance
	 *     SensorDistance returns SensorDistance
	 *
	 * Constraint:
	 *     name=String0?
	 * </pre>
	 */
	protected void sequence_SensorDistance(ISerializationContext context, SensorDistance semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns SensorExpr
	 *     SensorExpr returns SensorExpr
	 *
	 * Constraint:
	 *     (sensor=[Sensor|EString]? (variable+=Variable variable+=Variable*)?)
	 * </pre>
	 */
	protected void sequence_SensorExpr(ISerializationContext context, SensorExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Sensor returns SensorTime
	 *     SensorTime returns SensorTime
	 *
	 * Constraint:
	 *     name=String0?
	 * </pre>
	 */
	protected void sequence_SensorTime(ISerializationContext context, SensorTime semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Sensor returns Sensor
	 *     Sensor_Impl returns Sensor
	 *
	 * Constraint:
	 *     name=String0?
	 * </pre>
	 */
	protected void sequence_Sensor_Impl(ISerializationContext context, Sensor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns Type
	 *     Type_Impl returns Type
	 *
	 * Constraint:
	 *     {Type}
	 * </pre>
	 */
	protected void sequence_Type_Impl(ISerializationContext context, Type semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns VarExpr
	 *     VarExpr returns VarExpr
	 *
	 * Constraint:
	 *     (variableRef=[Variable|EString]? (variable+=Variable variable+=Variable*)?)
	 * </pre>
	 */
	protected void sequence_VarExpr(ISerializationContext context, VarExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     (name=String0? type=[Type|EString]?)
	 * </pre>
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
