/*
 * generated by Xtext 2.37.0
 */
grammar InternalMyDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.mydsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.mydsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

}

@parser::members {

 	private MyDslGrammarAccess grammarAccess;

    public InternalMyDslParser(TokenStream input, MyDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Type";
   	}

   	@Override
   	protected MyDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleType
entryRuleType returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTypeRule()); }
	iv_ruleType=ruleType
	{ $current=$iv_ruleType.current; }
	EOF;

// Rule Type
ruleType returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getTypeAccess().getType_ImplParserRuleCall_0());
		}
		this_Type_Impl_0=ruleType_Impl
		{
			$current = $this_Type_Impl_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getTypeAccess().getBoolParserRuleCall_1());
		}
		this_Bool_1=ruleBool
		{
			$current = $this_Bool_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getTypeAccess().getRealParserRuleCall_2());
		}
		this_Real_2=ruleReal
		{
			$current = $this_Real_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleExpression
entryRuleExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getExpressionRule()); }
	iv_ruleExpression=ruleExpression
	{ $current=$iv_ruleExpression.current; }
	EOF;

// Rule Expression
ruleExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getCallExprParserRuleCall_0());
		}
		this_CallExpr_0=ruleCallExpr
		{
			$current = $this_CallExpr_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getVarExprParserRuleCall_1());
		}
		this_VarExpr_1=ruleVarExpr
		{
			$current = $this_VarExpr_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getNegativeParserRuleCall_2());
		}
		this_Negative_2=ruleNegative
		{
			$current = $this_Negative_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getBinaryArithmeticParserRuleCall_3());
		}
		this_BinaryArithmetic_3=ruleBinaryArithmetic
		{
			$current = $this_BinaryArithmetic_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getNotParserRuleCall_4());
		}
		this_Not_4=ruleNot
		{
			$current = $this_Not_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getBinaryBoolParserRuleCall_5());
		}
		this_BinaryBool_5=ruleBinaryBool
		{
			$current = $this_BinaryBool_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getExpressionAccess().getSensorExprParserRuleCall_6());
		}
		this_SensorExpr_6=ruleSensorExpr
		{
			$current = $this_SensorExpr_6.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleVariable
entryRuleVariable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getVariableRule()); }
	iv_ruleVariable=ruleVariable
	{ $current=$iv_ruleVariable.current; }
	EOF;

// Rule Variable
ruleVariable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getVariableAccess().getVariableAction_0(),
					$current);
			}
		)
		otherlv_1='Variable'
		{
			newLeafNode(otherlv_1, grammarAccess.getVariableAccess().getVariableKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getVariableAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='name'
			{
				newLeafNode(otherlv_3, grammarAccess.getVariableAccess().getNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getVariableAccess().getNameString0ParserRuleCall_3_1_0());
					}
					lv_name_4_0=ruleString0
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getVariableRule());
						}
						set(
							$current,
							"name",
							lv_name_4_0,
							"org.xtext.example.mydsl.MyDsl.String0");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='type'
			{
				newLeafNode(otherlv_5, grammarAccess.getVariableAccess().getTypeKeyword_4_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getVariableRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getVariableAccess().getTypeTypeCrossReference_4_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getVariableAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleNegative
entryRuleNegative returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNegativeRule()); }
	iv_ruleNegative=ruleNegative
	{ $current=$iv_ruleNegative.current; }
	EOF;

// Rule Negative
ruleNegative returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Negative'
		{
			newLeafNode(otherlv_0, grammarAccess.getNegativeAccess().getNegativeKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getNegativeAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='variable'
			{
				newLeafNode(otherlv_2, grammarAccess.getNegativeAccess().getVariableKeyword_2_0());
			}
			otherlv_3='{'
			{
				newLeafNode(otherlv_3, grammarAccess.getNegativeAccess().getLeftCurlyBracketKeyword_2_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getNegativeAccess().getVariableVariableParserRuleCall_2_2_0());
					}
					lv_variable_4_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNegativeRule());
						}
						add(
							$current,
							"variable",
							lv_variable_4_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=','
				{
					newLeafNode(otherlv_5, grammarAccess.getNegativeAccess().getCommaKeyword_2_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getNegativeAccess().getVariableVariableParserRuleCall_2_3_1_0());
						}
						lv_variable_6_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getNegativeRule());
							}
							add(
								$current,
								"variable",
								lv_variable_6_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_7='}'
			{
				newLeafNode(otherlv_7, grammarAccess.getNegativeAccess().getRightCurlyBracketKeyword_2_4());
			}
		)?
		otherlv_8='expression'
		{
			newLeafNode(otherlv_8, grammarAccess.getNegativeAccess().getExpressionKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNegativeAccess().getExpressionExpressionParserRuleCall_4_0());
				}
				lv_expression_9_0=ruleExpression
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNegativeRule());
					}
					set(
						$current,
						"expression",
						lv_expression_9_0,
						"org.xtext.example.mydsl.MyDsl.Expression");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='}'
		{
			newLeafNode(otherlv_10, grammarAccess.getNegativeAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleBinaryArithmetic
entryRuleBinaryArithmetic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBinaryArithmeticRule()); }
	iv_ruleBinaryArithmetic=ruleBinaryArithmetic
	{ $current=$iv_ruleBinaryArithmetic.current; }
	EOF;

// Rule BinaryArithmetic
ruleBinaryArithmetic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='BinaryArithmetic'
		{
			newLeafNode(otherlv_0, grammarAccess.getBinaryArithmeticAccess().getBinaryArithmeticKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getBinaryArithmeticAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='operation'
			{
				newLeafNode(otherlv_2, grammarAccess.getBinaryArithmeticAccess().getOperationKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryArithmeticAccess().getOperationArithmeticOperationEnumRuleCall_2_1_0());
					}
					lv_operation_3_0=ruleArithmeticOperation
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryArithmeticRule());
						}
						set(
							$current,
							"operation",
							lv_operation_3_0,
							"org.xtext.example.mydsl.MyDsl.ArithmeticOperation");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_4='variable'
			{
				newLeafNode(otherlv_4, grammarAccess.getBinaryArithmeticAccess().getVariableKeyword_3_0());
			}
			otherlv_5='{'
			{
				newLeafNode(otherlv_5, grammarAccess.getBinaryArithmeticAccess().getLeftCurlyBracketKeyword_3_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryArithmeticAccess().getVariableVariableParserRuleCall_3_2_0());
					}
					lv_variable_6_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryArithmeticRule());
						}
						add(
							$current,
							"variable",
							lv_variable_6_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_7=','
				{
					newLeafNode(otherlv_7, grammarAccess.getBinaryArithmeticAccess().getCommaKeyword_3_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getBinaryArithmeticAccess().getVariableVariableParserRuleCall_3_3_1_0());
						}
						lv_variable_8_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getBinaryArithmeticRule());
							}
							add(
								$current,
								"variable",
								lv_variable_8_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_9='}'
			{
				newLeafNode(otherlv_9, grammarAccess.getBinaryArithmeticAccess().getRightCurlyBracketKeyword_3_4());
			}
		)?
		otherlv_10='expression'
		{
			newLeafNode(otherlv_10, grammarAccess.getBinaryArithmeticAccess().getExpressionKeyword_4());
		}
		otherlv_11='{'
		{
			newLeafNode(otherlv_11, grammarAccess.getBinaryArithmeticAccess().getLeftCurlyBracketKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBinaryArithmeticAccess().getExpressionExpressionParserRuleCall_6_0());
				}
				lv_expression_12_0=ruleExpression
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBinaryArithmeticRule());
					}
					add(
						$current,
						"expression",
						lv_expression_12_0,
						"org.xtext.example.mydsl.MyDsl.Expression");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_13=','
			{
				newLeafNode(otherlv_13, grammarAccess.getBinaryArithmeticAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryArithmeticAccess().getExpressionExpressionParserRuleCall_7_1_0());
					}
					lv_expression_14_0=ruleExpression
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryArithmeticRule());
						}
						add(
							$current,
							"expression",
							lv_expression_14_0,
							"org.xtext.example.mydsl.MyDsl.Expression");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getBinaryArithmeticAccess().getRightCurlyBracketKeyword_8());
		}
		otherlv_16='}'
		{
			newLeafNode(otherlv_16, grammarAccess.getBinaryArithmeticAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleType_Impl
entryRuleType_Impl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getType_ImplRule()); }
	iv_ruleType_Impl=ruleType_Impl
	{ $current=$iv_ruleType_Impl.current; }
	EOF;

// Rule Type_Impl
ruleType_Impl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getType_ImplAccess().getTypeAction_0(),
					$current);
			}
		)
		otherlv_1='Type'
		{
			newLeafNode(otherlv_1, grammarAccess.getType_ImplAccess().getTypeKeyword_1());
		}
	)
;

// Entry rule entryRuleString0
entryRuleString0 returns [String current=null]:
	{ newCompositeNode(grammarAccess.getString0Rule()); }
	iv_ruleString0=ruleString0
	{ $current=$iv_ruleString0.current.getText(); }
	EOF;

// Rule String0
ruleString0 returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='String'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getString0Access().getStringKeyword());
	}
;

// Entry rule entryRuleBool
entryRuleBool returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBoolRule()); }
	iv_ruleBool=ruleBool
	{ $current=$iv_ruleBool.current; }
	EOF;

// Rule Bool
ruleBool returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getBoolAccess().getBoolAction_0(),
					$current);
			}
		)
		otherlv_1='Bool'
		{
			newLeafNode(otherlv_1, grammarAccess.getBoolAccess().getBoolKeyword_1());
		}
	)
;

// Entry rule entryRuleReal
entryRuleReal returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRealRule()); }
	iv_ruleReal=ruleReal
	{ $current=$iv_ruleReal.current; }
	EOF;

// Rule Real
ruleReal returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getRealAccess().getRealAction_0(),
					$current);
			}
		)
		otherlv_1='Real'
		{
			newLeafNode(otherlv_1, grammarAccess.getRealAccess().getRealKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getRealAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='unit'
			{
				newLeafNode(otherlv_3, grammarAccess.getRealAccess().getUnitKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRealAccess().getUnitUnitEnumRuleCall_3_1_0());
					}
					lv_unit_4_0=ruleUnit
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRealRule());
						}
						set(
							$current,
							"unit",
							lv_unit_4_0,
							"org.xtext.example.mydsl.MyDsl.Unit");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getRealAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleCallExpr
entryRuleCallExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCallExprRule()); }
	iv_ruleCallExpr=ruleCallExpr
	{ $current=$iv_ruleCallExpr.current; }
	EOF;

// Rule CallExpr
ruleCallExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getCallExprAccess().getCallExprAction_0(),
					$current);
			}
		)
		otherlv_1='CallExpr'
		{
			newLeafNode(otherlv_1, grammarAccess.getCallExprAccess().getCallExprKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getCallExprAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='fonction'
			{
				newLeafNode(otherlv_3, grammarAccess.getCallExprAccess().getFonctionKeyword_3_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getCallExprRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getCallExprAccess().getFonctionFonctionCrossReference_3_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='variable'
			{
				newLeafNode(otherlv_5, grammarAccess.getCallExprAccess().getVariableKeyword_4_0());
			}
			otherlv_6='{'
			{
				newLeafNode(otherlv_6, grammarAccess.getCallExprAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getCallExprAccess().getVariableVariableParserRuleCall_4_2_0());
					}
					lv_variable_7_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCallExprRule());
						}
						add(
							$current,
							"variable",
							lv_variable_7_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_8=','
				{
					newLeafNode(otherlv_8, grammarAccess.getCallExprAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getCallExprAccess().getVariableVariableParserRuleCall_4_3_1_0());
						}
						lv_variable_9_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getCallExprRule());
							}
							add(
								$current,
								"variable",
								lv_variable_9_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_10='}'
			{
				newLeafNode(otherlv_10, grammarAccess.getCallExprAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		(
			otherlv_11='parameters'
			{
				newLeafNode(otherlv_11, grammarAccess.getCallExprAccess().getParametersKeyword_5_0());
			}
			otherlv_12='{'
			{
				newLeafNode(otherlv_12, grammarAccess.getCallExprAccess().getLeftCurlyBracketKeyword_5_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getCallExprAccess().getParametersExpressionParserRuleCall_5_2_0());
					}
					lv_parameters_13_0=ruleExpression
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCallExprRule());
						}
						add(
							$current,
							"parameters",
							lv_parameters_13_0,
							"org.xtext.example.mydsl.MyDsl.Expression");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_14=','
				{
					newLeafNode(otherlv_14, grammarAccess.getCallExprAccess().getCommaKeyword_5_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getCallExprAccess().getParametersExpressionParserRuleCall_5_3_1_0());
						}
						lv_parameters_15_0=ruleExpression
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getCallExprRule());
							}
							add(
								$current,
								"parameters",
								lv_parameters_15_0,
								"org.xtext.example.mydsl.MyDsl.Expression");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_16='}'
			{
				newLeafNode(otherlv_16, grammarAccess.getCallExprAccess().getRightCurlyBracketKeyword_5_4());
			}
		)?
		otherlv_17='}'
		{
			newLeafNode(otherlv_17, grammarAccess.getCallExprAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleVarExpr
entryRuleVarExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getVarExprRule()); }
	iv_ruleVarExpr=ruleVarExpr
	{ $current=$iv_ruleVarExpr.current; }
	EOF;

// Rule VarExpr
ruleVarExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getVarExprAccess().getVarExprAction_0(),
					$current);
			}
		)
		otherlv_1='VarExpr'
		{
			newLeafNode(otherlv_1, grammarAccess.getVarExprAccess().getVarExprKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getVarExprAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='variableRef'
			{
				newLeafNode(otherlv_3, grammarAccess.getVarExprAccess().getVariableRefKeyword_3_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getVarExprRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getVarExprAccess().getVariableRefVariableCrossReference_3_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='variable'
			{
				newLeafNode(otherlv_5, grammarAccess.getVarExprAccess().getVariableKeyword_4_0());
			}
			otherlv_6='{'
			{
				newLeafNode(otherlv_6, grammarAccess.getVarExprAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getVarExprAccess().getVariableVariableParserRuleCall_4_2_0());
					}
					lv_variable_7_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getVarExprRule());
						}
						add(
							$current,
							"variable",
							lv_variable_7_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_8=','
				{
					newLeafNode(otherlv_8, grammarAccess.getVarExprAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getVarExprAccess().getVariableVariableParserRuleCall_4_3_1_0());
						}
						lv_variable_9_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getVarExprRule());
							}
							add(
								$current,
								"variable",
								lv_variable_9_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_10='}'
			{
				newLeafNode(otherlv_10, grammarAccess.getVarExprAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getVarExprAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleNot
entryRuleNot returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNotRule()); }
	iv_ruleNot=ruleNot
	{ $current=$iv_ruleNot.current; }
	EOF;

// Rule Not
ruleNot returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Not'
		{
			newLeafNode(otherlv_0, grammarAccess.getNotAccess().getNotKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getNotAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='variable'
			{
				newLeafNode(otherlv_2, grammarAccess.getNotAccess().getVariableKeyword_2_0());
			}
			otherlv_3='{'
			{
				newLeafNode(otherlv_3, grammarAccess.getNotAccess().getLeftCurlyBracketKeyword_2_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getNotAccess().getVariableVariableParserRuleCall_2_2_0());
					}
					lv_variable_4_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNotRule());
						}
						add(
							$current,
							"variable",
							lv_variable_4_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=','
				{
					newLeafNode(otherlv_5, grammarAccess.getNotAccess().getCommaKeyword_2_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getNotAccess().getVariableVariableParserRuleCall_2_3_1_0());
						}
						lv_variable_6_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getNotRule());
							}
							add(
								$current,
								"variable",
								lv_variable_6_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_7='}'
			{
				newLeafNode(otherlv_7, grammarAccess.getNotAccess().getRightCurlyBracketKeyword_2_4());
			}
		)?
		otherlv_8='expression'
		{
			newLeafNode(otherlv_8, grammarAccess.getNotAccess().getExpressionKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNotAccess().getExpressionExpressionParserRuleCall_4_0());
				}
				lv_expression_9_0=ruleExpression
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNotRule());
					}
					set(
						$current,
						"expression",
						lv_expression_9_0,
						"org.xtext.example.mydsl.MyDsl.Expression");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='}'
		{
			newLeafNode(otherlv_10, grammarAccess.getNotAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleBinaryBool
entryRuleBinaryBool returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBinaryBoolRule()); }
	iv_ruleBinaryBool=ruleBinaryBool
	{ $current=$iv_ruleBinaryBool.current; }
	EOF;

// Rule BinaryBool
ruleBinaryBool returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='BinaryBool'
		{
			newLeafNode(otherlv_0, grammarAccess.getBinaryBoolAccess().getBinaryBoolKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getBinaryBoolAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='operation'
			{
				newLeafNode(otherlv_2, grammarAccess.getBinaryBoolAccess().getOperationKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryBoolAccess().getOperationBoolOperationEnumRuleCall_2_1_0());
					}
					lv_operation_3_0=ruleBoolOperation
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryBoolRule());
						}
						set(
							$current,
							"operation",
							lv_operation_3_0,
							"org.xtext.example.mydsl.MyDsl.BoolOperation");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_4='variable'
			{
				newLeafNode(otherlv_4, grammarAccess.getBinaryBoolAccess().getVariableKeyword_3_0());
			}
			otherlv_5='{'
			{
				newLeafNode(otherlv_5, grammarAccess.getBinaryBoolAccess().getLeftCurlyBracketKeyword_3_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryBoolAccess().getVariableVariableParserRuleCall_3_2_0());
					}
					lv_variable_6_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryBoolRule());
						}
						add(
							$current,
							"variable",
							lv_variable_6_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_7=','
				{
					newLeafNode(otherlv_7, grammarAccess.getBinaryBoolAccess().getCommaKeyword_3_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getBinaryBoolAccess().getVariableVariableParserRuleCall_3_3_1_0());
						}
						lv_variable_8_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getBinaryBoolRule());
							}
							add(
								$current,
								"variable",
								lv_variable_8_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_9='}'
			{
				newLeafNode(otherlv_9, grammarAccess.getBinaryBoolAccess().getRightCurlyBracketKeyword_3_4());
			}
		)?
		otherlv_10='expression'
		{
			newLeafNode(otherlv_10, grammarAccess.getBinaryBoolAccess().getExpressionKeyword_4());
		}
		otherlv_11='{'
		{
			newLeafNode(otherlv_11, grammarAccess.getBinaryBoolAccess().getLeftCurlyBracketKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBinaryBoolAccess().getExpressionExpressionParserRuleCall_6_0());
				}
				lv_expression_12_0=ruleExpression
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBinaryBoolRule());
					}
					add(
						$current,
						"expression",
						lv_expression_12_0,
						"org.xtext.example.mydsl.MyDsl.Expression");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_13=','
			{
				newLeafNode(otherlv_13, grammarAccess.getBinaryBoolAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBinaryBoolAccess().getExpressionExpressionParserRuleCall_7_1_0());
					}
					lv_expression_14_0=ruleExpression
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBinaryBoolRule());
						}
						add(
							$current,
							"expression",
							lv_expression_14_0,
							"org.xtext.example.mydsl.MyDsl.Expression");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getBinaryBoolAccess().getRightCurlyBracketKeyword_8());
		}
		otherlv_16='}'
		{
			newLeafNode(otherlv_16, grammarAccess.getBinaryBoolAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleSensorExpr
entryRuleSensorExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSensorExprRule()); }
	iv_ruleSensorExpr=ruleSensorExpr
	{ $current=$iv_ruleSensorExpr.current; }
	EOF;

// Rule SensorExpr
ruleSensorExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getSensorExprAccess().getSensorExprAction_0(),
					$current);
			}
		)
		otherlv_1='SensorExpr'
		{
			newLeafNode(otherlv_1, grammarAccess.getSensorExprAccess().getSensorExprKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSensorExprAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='sensor'
			{
				newLeafNode(otherlv_3, grammarAccess.getSensorExprAccess().getSensorKeyword_3_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSensorExprRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getSensorExprAccess().getSensorSensorCrossReference_3_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='variable'
			{
				newLeafNode(otherlv_5, grammarAccess.getSensorExprAccess().getVariableKeyword_4_0());
			}
			otherlv_6='{'
			{
				newLeafNode(otherlv_6, grammarAccess.getSensorExprAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSensorExprAccess().getVariableVariableParserRuleCall_4_2_0());
					}
					lv_variable_7_0=ruleVariable
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSensorExprRule());
						}
						add(
							$current,
							"variable",
							lv_variable_7_0,
							"org.xtext.example.mydsl.MyDsl.Variable");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_8=','
				{
					newLeafNode(otherlv_8, grammarAccess.getSensorExprAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getSensorExprAccess().getVariableVariableParserRuleCall_4_3_1_0());
						}
						lv_variable_9_0=ruleVariable
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getSensorExprRule());
							}
							add(
								$current,
								"variable",
								lv_variable_9_0,
								"org.xtext.example.mydsl.MyDsl.Variable");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_10='}'
			{
				newLeafNode(otherlv_10, grammarAccess.getSensorExprAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getSensorExprAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleSensor_Impl
entryRuleSensor_Impl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSensor_ImplRule()); }
	iv_ruleSensor_Impl=ruleSensor_Impl
	{ $current=$iv_ruleSensor_Impl.current; }
	EOF;

// Rule Sensor_Impl
ruleSensor_Impl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getSensor_ImplAccess().getSensorAction_0(),
					$current);
			}
		)
		otherlv_1='Sensor'
		{
			newLeafNode(otherlv_1, grammarAccess.getSensor_ImplAccess().getSensorKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSensor_ImplAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='name'
			{
				newLeafNode(otherlv_3, grammarAccess.getSensor_ImplAccess().getNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSensor_ImplAccess().getNameString0ParserRuleCall_3_1_0());
					}
					lv_name_4_0=ruleString0
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSensor_ImplRule());
						}
						set(
							$current,
							"name",
							lv_name_4_0,
							"org.xtext.example.mydsl.MyDsl.String0");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getSensor_ImplAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleSensorDistance
entryRuleSensorDistance returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSensorDistanceRule()); }
	iv_ruleSensorDistance=ruleSensorDistance
	{ $current=$iv_ruleSensorDistance.current; }
	EOF;

// Rule SensorDistance
ruleSensorDistance returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getSensorDistanceAccess().getSensorDistanceAction_0(),
					$current);
			}
		)
		otherlv_1='SensorDistance'
		{
			newLeafNode(otherlv_1, grammarAccess.getSensorDistanceAccess().getSensorDistanceKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSensorDistanceAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='name'
			{
				newLeafNode(otherlv_3, grammarAccess.getSensorDistanceAccess().getNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSensorDistanceAccess().getNameString0ParserRuleCall_3_1_0());
					}
					lv_name_4_0=ruleString0
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSensorDistanceRule());
						}
						set(
							$current,
							"name",
							lv_name_4_0,
							"org.xtext.example.mydsl.MyDsl.String0");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getSensorDistanceAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleSensorTime
entryRuleSensorTime returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSensorTimeRule()); }
	iv_ruleSensorTime=ruleSensorTime
	{ $current=$iv_ruleSensorTime.current; }
	EOF;

// Rule SensorTime
ruleSensorTime returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getSensorTimeAccess().getSensorTimeAction_0(),
					$current);
			}
		)
		otherlv_1='SensorTime'
		{
			newLeafNode(otherlv_1, grammarAccess.getSensorTimeAccess().getSensorTimeKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSensorTimeAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='name'
			{
				newLeafNode(otherlv_3, grammarAccess.getSensorTimeAccess().getNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSensorTimeAccess().getNameString0ParserRuleCall_3_1_0());
					}
					lv_name_4_0=ruleString0
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSensorTimeRule());
						}
						set(
							$current,
							"name",
							lv_name_4_0,
							"org.xtext.example.mydsl.MyDsl.String0");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getSensorTimeAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Rule Unit
ruleUnit returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='MM'
			{
				$current = grammarAccess.getUnitAccess().getMMEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getUnitAccess().getMMEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='KM'
			{
				$current = grammarAccess.getUnitAccess().getKMEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getUnitAccess().getKMEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='CM'
			{
				$current = grammarAccess.getUnitAccess().getCMEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getUnitAccess().getCMEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='M'
			{
				$current = grammarAccess.getUnitAccess().getMEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getUnitAccess().getMEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='DM'
			{
				$current = grammarAccess.getUnitAccess().getDMEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getUnitAccess().getDMEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='HM'
			{
				$current = grammarAccess.getUnitAccess().getHMEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getUnitAccess().getHMEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='DAM'
			{
				$current = grammarAccess.getUnitAccess().getDAMEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getUnitAccess().getDAMEnumLiteralDeclaration_6());
			}
		)
		    |
		(
			enumLiteral_7='RAD'
			{
				$current = grammarAccess.getUnitAccess().getRADEnumLiteralDeclaration_7().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_7, grammarAccess.getUnitAccess().getRADEnumLiteralDeclaration_7());
			}
		)
	)
;

// Rule BoolOperation
ruleBoolOperation returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='INF'
			{
				$current = grammarAccess.getBoolOperationAccess().getINFEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getBoolOperationAccess().getINFEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='SUP'
			{
				$current = grammarAccess.getBoolOperationAccess().getSUPEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getBoolOperationAccess().getSUPEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='INF_EQ'
			{
				$current = grammarAccess.getBoolOperationAccess().getINF_EQEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getBoolOperationAccess().getINF_EQEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='EQ'
			{
				$current = grammarAccess.getBoolOperationAccess().getEQEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getBoolOperationAccess().getEQEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='SUP_EQ'
			{
				$current = grammarAccess.getBoolOperationAccess().getSUP_EQEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getBoolOperationAccess().getSUP_EQEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='NEQ'
			{
				$current = grammarAccess.getBoolOperationAccess().getNEQEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getBoolOperationAccess().getNEQEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='OR'
			{
				$current = grammarAccess.getBoolOperationAccess().getOREnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getBoolOperationAccess().getOREnumLiteralDeclaration_6());
			}
		)
		    |
		(
			enumLiteral_7='AND'
			{
				$current = grammarAccess.getBoolOperationAccess().getANDEnumLiteralDeclaration_7().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_7, grammarAccess.getBoolOperationAccess().getANDEnumLiteralDeclaration_7());
			}
		)
	)
;

// Rule ArithmeticOperation
ruleArithmeticOperation returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='ADD'
			{
				$current = grammarAccess.getArithmeticOperationAccess().getADDEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getArithmeticOperationAccess().getADDEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='SUB'
			{
				$current = grammarAccess.getArithmeticOperationAccess().getSUBEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getArithmeticOperationAccess().getSUBEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='DIV'
			{
				$current = grammarAccess.getArithmeticOperationAccess().getDIVEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getArithmeticOperationAccess().getDIVEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='MULT'
			{
				$current = grammarAccess.getArithmeticOperationAccess().getMULTEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getArithmeticOperationAccess().getMULTEnumLiteralDeclaration_3());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
