#

pluginName = RoboML Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Fonction_type = Fonction
_UI_Instruction_type = Instruction
_UI_RobotProgram_type = Robot Program
_UI_BooleanExpr_type = Boolean Expr
_UI_Loop_type = Loop
_UI_Condition_type = Condition
_UI_Variable_type = Variable
_UI_Expression_type = Expression
_UI_ArithmeticExpr_type = Arithmetic Expr
_UI_Declaration_type = Declaration
_UI_Type_type = Type
_UI_Bool_type = Bool
_UI_Real_type = Real
_UI_Call_type = Call
_UI_Assignment_type = Assignment
_UI_CallExpr_type = Call Expr
_UI_Sensor_type = Sensor
_UI_Parameter_type = Parameter
_UI_VarExpr_type = Var Expr
_UI_return_type = return
_UI_Block_type = Block
_UI_Movement_type = Movement
_UI_Forward_type = Forward
_UI_Rotate_type = Rotate
_UI_Left_type = Left
_UI_Backward_type = Backward
_UI_Right_type = Right
_UI_Speed_type = Speed
_UI_SensorDistance_type = Sensor Distance
_UI_SensorTime_type = Sensor Time
_UI_Negative_type = Negative
_UI_BinaryArithmetic_type = Binary Arithmetic
_UI_Not_type = Not
_UI_BinaryBool_type = Binary Bool
_UI_SensorExpr_type = Sensor Expr
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Fonction_parameter_feature = Parameter
_UI_Fonction_name_feature = Name
_UI_Fonction_typeReturn_feature = Type Return
_UI_RobotProgram_declaration_feature = Declaration
_UI_RobotProgram_instruction_feature = Instruction
_UI_RobotProgram_expression_feature = Expression
_UI_Loop_booleanexpr_feature = Booleanexpr
_UI_Loop_instruction_feature = Instruction
_UI_Condition_booleanexpr_feature = Booleanexpr
_UI_Condition_if_feature = If
_UI_Condition_else_feature = Else
_UI_Variable_type_feature = Type
_UI_Variable_name_feature = Name
_UI_Expression_variable_feature = Variable
_UI_Real_unit_feature = Unit
_UI_Call_parameters_feature = Parameters
_UI_Call_fonction_feature = Fonction
_UI_Assignment_expression_feature = Expression
_UI_Assignment_variable_feature = Variable
_UI_CallExpr_parameters_feature = Parameters
_UI_CallExpr_fonction_feature = Fonction
_UI_Sensor_name_feature = Name
_UI_Parameter_type_feature = Type
_UI_Parameter_name_feature = Name
_UI_VarExpr_variableRef_feature = Variable Ref
_UI_return_expression_feature = Expression
_UI_Block_instruction_feature = Instruction
_UI_Movement_parameters_feature = Parameters
_UI_Speed_parameters_feature = Parameters
_UI_Negative_expression_feature = Expression
_UI_BinaryArithmetic_operation_feature = Operation
_UI_BinaryArithmetic_expression_feature = Expression
_UI_Not_expression_feature = Expression
_UI_BinaryBool_operation_feature = Operation
_UI_BinaryBool_expression_feature = Expression
_UI_SensorExpr_sensor_feature = Sensor
_UI_Unknown_feature = Unspecified

_UI_Unit_MM_literal = MM
_UI_Unit_KM_literal = KM
_UI_Unit_CM_literal = CM
_UI_Unit_M_literal = M
_UI_Unit_DM_literal = DM
_UI_Unit_HM_literal = HM
_UI_Unit_DAM_literal = DAM
_UI_Unit_RAD_literal = RAD
_UI_BoolOperation_INF_literal = INF
_UI_BoolOperation_SUP_literal = SUP
_UI_BoolOperation_INF_EQ_literal = INF_EQ
_UI_BoolOperation_EQ_literal = EQ
_UI_BoolOperation_SUP_EQ_literal = SUP_EQ
_UI_BoolOperation_NEQ_literal = NEQ
_UI_BoolOperation_OR_literal = OR
_UI_BoolOperation_AND_literal = AND
_UI_ArithmeticOperation_ADD_literal = ADD
_UI_ArithmeticOperation_SUB_literal = SUB
_UI_ArithmeticOperation_DIV_literal = DIV
_UI_ArithmeticOperation_MULT_literal = MULT
