/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getSensorAccess().getAlternatives(), "rule__Sensor__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getUnitAccess().getAlternatives(), "rule__Unit__Alternatives");
			builder.put(grammarAccess.getBoolOperationAccess().getAlternatives(), "rule__BoolOperation__Alternatives");
			builder.put(grammarAccess.getArithmeticOperationAccess().getAlternatives(), "rule__ArithmeticOperation__Alternatives");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_3(), "rule__Variable__Group_3__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_4(), "rule__Variable__Group_4__0");
			builder.put(grammarAccess.getNegativeAccess().getGroup(), "rule__Negative__Group__0");
			builder.put(grammarAccess.getNegativeAccess().getGroup_2(), "rule__Negative__Group_2__0");
			builder.put(grammarAccess.getNegativeAccess().getGroup_2_3(), "rule__Negative__Group_2_3__0");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getGroup(), "rule__BinaryArithmetic__Group__0");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getGroup_2(), "rule__BinaryArithmetic__Group_2__0");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getGroup_3(), "rule__BinaryArithmetic__Group_3__0");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getGroup_3_3(), "rule__BinaryArithmetic__Group_3_3__0");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getGroup_7(), "rule__BinaryArithmetic__Group_7__0");
			builder.put(grammarAccess.getType_ImplAccess().getGroup(), "rule__Type_Impl__Group__0");
			builder.put(grammarAccess.getBoolAccess().getGroup(), "rule__Bool__Group__0");
			builder.put(grammarAccess.getRealAccess().getGroup(), "rule__Real__Group__0");
			builder.put(grammarAccess.getRealAccess().getGroup_3(), "rule__Real__Group_3__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup(), "rule__CallExpr__Group__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup_3(), "rule__CallExpr__Group_3__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup_4(), "rule__CallExpr__Group_4__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup_4_3(), "rule__CallExpr__Group_4_3__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup_5(), "rule__CallExpr__Group_5__0");
			builder.put(grammarAccess.getCallExprAccess().getGroup_5_3(), "rule__CallExpr__Group_5_3__0");
			builder.put(grammarAccess.getVarExprAccess().getGroup(), "rule__VarExpr__Group__0");
			builder.put(grammarAccess.getVarExprAccess().getGroup_3(), "rule__VarExpr__Group_3__0");
			builder.put(grammarAccess.getVarExprAccess().getGroup_4(), "rule__VarExpr__Group_4__0");
			builder.put(grammarAccess.getVarExprAccess().getGroup_4_3(), "rule__VarExpr__Group_4_3__0");
			builder.put(grammarAccess.getNotAccess().getGroup(), "rule__Not__Group__0");
			builder.put(grammarAccess.getNotAccess().getGroup_2(), "rule__Not__Group_2__0");
			builder.put(grammarAccess.getNotAccess().getGroup_2_3(), "rule__Not__Group_2_3__0");
			builder.put(grammarAccess.getBinaryBoolAccess().getGroup(), "rule__BinaryBool__Group__0");
			builder.put(grammarAccess.getBinaryBoolAccess().getGroup_2(), "rule__BinaryBool__Group_2__0");
			builder.put(grammarAccess.getBinaryBoolAccess().getGroup_3(), "rule__BinaryBool__Group_3__0");
			builder.put(grammarAccess.getBinaryBoolAccess().getGroup_3_3(), "rule__BinaryBool__Group_3_3__0");
			builder.put(grammarAccess.getBinaryBoolAccess().getGroup_7(), "rule__BinaryBool__Group_7__0");
			builder.put(grammarAccess.getSensorExprAccess().getGroup(), "rule__SensorExpr__Group__0");
			builder.put(grammarAccess.getSensorExprAccess().getGroup_3(), "rule__SensorExpr__Group_3__0");
			builder.put(grammarAccess.getSensorExprAccess().getGroup_4(), "rule__SensorExpr__Group_4__0");
			builder.put(grammarAccess.getSensorExprAccess().getGroup_4_3(), "rule__SensorExpr__Group_4_3__0");
			builder.put(grammarAccess.getFonctionAccess().getGroup(), "rule__Fonction__Group__0");
			builder.put(grammarAccess.getFonctionAccess().getGroup_3(), "rule__Fonction__Group_3__0");
			builder.put(grammarAccess.getFonctionAccess().getGroup_4(), "rule__Fonction__Group_4__0");
			builder.put(grammarAccess.getFonctionAccess().getGroup_4_3(), "rule__Fonction__Group_4_3__0");
			builder.put(grammarAccess.getFonctionAccess().getGroup_5(), "rule__Fonction__Group_5__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_3(), "rule__Parameter__Group_3__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_4(), "rule__Parameter__Group_4__0");
			builder.put(grammarAccess.getSensor_ImplAccess().getGroup(), "rule__Sensor_Impl__Group__0");
			builder.put(grammarAccess.getSensor_ImplAccess().getGroup_3(), "rule__Sensor_Impl__Group_3__0");
			builder.put(grammarAccess.getSensorDistanceAccess().getGroup(), "rule__SensorDistance__Group__0");
			builder.put(grammarAccess.getSensorDistanceAccess().getGroup_3(), "rule__SensorDistance__Group_3__0");
			builder.put(grammarAccess.getSensorTimeAccess().getGroup(), "rule__SensorTime__Group__0");
			builder.put(grammarAccess.getSensorTimeAccess().getGroup_3(), "rule__SensorTime__Group_3__0");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_3_1(), "rule__Variable__NameAssignment_3_1");
			builder.put(grammarAccess.getVariableAccess().getTypeAssignment_4_1(), "rule__Variable__TypeAssignment_4_1");
			builder.put(grammarAccess.getNegativeAccess().getVariableAssignment_2_2(), "rule__Negative__VariableAssignment_2_2");
			builder.put(grammarAccess.getNegativeAccess().getVariableAssignment_2_3_1(), "rule__Negative__VariableAssignment_2_3_1");
			builder.put(grammarAccess.getNegativeAccess().getExpressionAssignment_4(), "rule__Negative__ExpressionAssignment_4");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getOperationAssignment_2_1(), "rule__BinaryArithmetic__OperationAssignment_2_1");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getVariableAssignment_3_2(), "rule__BinaryArithmetic__VariableAssignment_3_2");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getVariableAssignment_3_3_1(), "rule__BinaryArithmetic__VariableAssignment_3_3_1");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getExpressionAssignment_6(), "rule__BinaryArithmetic__ExpressionAssignment_6");
			builder.put(grammarAccess.getBinaryArithmeticAccess().getExpressionAssignment_7_1(), "rule__BinaryArithmetic__ExpressionAssignment_7_1");
			builder.put(grammarAccess.getRealAccess().getUnitAssignment_3_1(), "rule__Real__UnitAssignment_3_1");
			builder.put(grammarAccess.getCallExprAccess().getFonctionAssignment_3_1(), "rule__CallExpr__FonctionAssignment_3_1");
			builder.put(grammarAccess.getCallExprAccess().getVariableAssignment_4_2(), "rule__CallExpr__VariableAssignment_4_2");
			builder.put(grammarAccess.getCallExprAccess().getVariableAssignment_4_3_1(), "rule__CallExpr__VariableAssignment_4_3_1");
			builder.put(grammarAccess.getCallExprAccess().getParametersAssignment_5_2(), "rule__CallExpr__ParametersAssignment_5_2");
			builder.put(grammarAccess.getCallExprAccess().getParametersAssignment_5_3_1(), "rule__CallExpr__ParametersAssignment_5_3_1");
			builder.put(grammarAccess.getVarExprAccess().getVariableRefAssignment_3_1(), "rule__VarExpr__VariableRefAssignment_3_1");
			builder.put(grammarAccess.getVarExprAccess().getVariableAssignment_4_2(), "rule__VarExpr__VariableAssignment_4_2");
			builder.put(grammarAccess.getVarExprAccess().getVariableAssignment_4_3_1(), "rule__VarExpr__VariableAssignment_4_3_1");
			builder.put(grammarAccess.getNotAccess().getVariableAssignment_2_2(), "rule__Not__VariableAssignment_2_2");
			builder.put(grammarAccess.getNotAccess().getVariableAssignment_2_3_1(), "rule__Not__VariableAssignment_2_3_1");
			builder.put(grammarAccess.getNotAccess().getExpressionAssignment_4(), "rule__Not__ExpressionAssignment_4");
			builder.put(grammarAccess.getBinaryBoolAccess().getOperationAssignment_2_1(), "rule__BinaryBool__OperationAssignment_2_1");
			builder.put(grammarAccess.getBinaryBoolAccess().getVariableAssignment_3_2(), "rule__BinaryBool__VariableAssignment_3_2");
			builder.put(grammarAccess.getBinaryBoolAccess().getVariableAssignment_3_3_1(), "rule__BinaryBool__VariableAssignment_3_3_1");
			builder.put(grammarAccess.getBinaryBoolAccess().getExpressionAssignment_6(), "rule__BinaryBool__ExpressionAssignment_6");
			builder.put(grammarAccess.getBinaryBoolAccess().getExpressionAssignment_7_1(), "rule__BinaryBool__ExpressionAssignment_7_1");
			builder.put(grammarAccess.getSensorExprAccess().getSensorAssignment_3_1(), "rule__SensorExpr__SensorAssignment_3_1");
			builder.put(grammarAccess.getSensorExprAccess().getVariableAssignment_4_2(), "rule__SensorExpr__VariableAssignment_4_2");
			builder.put(grammarAccess.getSensorExprAccess().getVariableAssignment_4_3_1(), "rule__SensorExpr__VariableAssignment_4_3_1");
			builder.put(grammarAccess.getFonctionAccess().getNameAssignment_3_1(), "rule__Fonction__NameAssignment_3_1");
			builder.put(grammarAccess.getFonctionAccess().getParameterAssignment_4_2(), "rule__Fonction__ParameterAssignment_4_2");
			builder.put(grammarAccess.getFonctionAccess().getParameterAssignment_4_3_1(), "rule__Fonction__ParameterAssignment_4_3_1");
			builder.put(grammarAccess.getFonctionAccess().getTypeReturnAssignment_5_1(), "rule__Fonction__TypeReturnAssignment_5_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_3_1(), "rule__Parameter__NameAssignment_3_1");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_4_1(), "rule__Parameter__TypeAssignment_4_1");
			builder.put(grammarAccess.getSensor_ImplAccess().getNameAssignment_3_1(), "rule__Sensor_Impl__NameAssignment_3_1");
			builder.put(grammarAccess.getSensorDistanceAccess().getNameAssignment_3_1(), "rule__SensorDistance__NameAssignment_3_1");
			builder.put(grammarAccess.getSensorTimeAccess().getNameAssignment_3_1(), "rule__SensorTime__NameAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
