/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import roboML.BooleanExpr;
import roboML.Declaration;
import roboML.Expression;
import roboML.Instruction;
import roboML.Loop;
import roboML.RobotProgram;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final RobotProgram robotProgram, @Extension final IFormattableDocument document) {
    EList<Declaration> _declaration = robotProgram.getDeclaration();
    for (final Declaration declaration : _declaration) {
      document.<Declaration>format(declaration);
    }
    EList<Instruction> _instruction = robotProgram.getInstruction();
    for (final Instruction instruction : _instruction) {
      document.<Instruction>format(instruction);
    }
    EList<Expression> _expression = robotProgram.getExpression();
    for (final Expression expression : _expression) {
      document.<Expression>format(expression);
    }
  }

  protected void _format(final Loop loop, @Extension final IFormattableDocument document) {
    document.<BooleanExpr>format(loop.getBooleanexpr());
    EList<Instruction> _instruction = loop.getInstruction();
    for (final Instruction instruction : _instruction) {
      document.<Instruction>format(instruction);
    }
  }

  @XbaseGenerated
  public void format(final Object loop, final IFormattableDocument document) {
    if (loop instanceof XtextResource) {
      _format((XtextResource)loop, document);
      return;
    } else if (loop instanceof Loop) {
      _format((Loop)loop, document);
      return;
    } else if (loop instanceof RobotProgram) {
      _format((RobotProgram)loop, document);
      return;
    } else if (loop instanceof EObject) {
      _format((EObject)loop, document);
      return;
    } else if (loop == null) {
      _format((Void)null, document);
      return;
    } else if (loop != null) {
      _format(loop, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(loop, document).toString());
    }
  }
}
