/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final /* Negative */Object negative, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nvariable cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nexpression cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* BinaryArithmetic */Object binaryArithmetic, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nvariable cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nexpression cannot be resolved"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final Object negative, final IFormattableDocument document) {
    if (negative instanceof XtextResource) {
      _format((XtextResource)negative, document);
      return;
    } else if (negative instanceof EObject) {
      _format((EObject)negative, document);
      return;
    } else if (negative == null) {
      _format((Void)null, document);
      return;
    } else if (negative != null) {
      _format(negative, document);
      return;
    } else if (negative != null) {
      _format(negative, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(negative, document).toString());
    }
  }
}
